version: '3.8'

services:
  # web:
  #   image: node:22
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   command: npm run dev
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development

  redis:
    image: docker.io/redis/redis-stack-server:latest
    ports:
      - '6379:6379'
