version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
volumes:
  mongodb:
